#!/bin/bash
# +----------------------------------------------------------------------------+
# | MM16D v0.1 * Grow house control device                                     |
# | Copyright (C) 2023 Pozsár Zsolt <pozsarzs@gmail.com>                       |
# | clone                                                                      |
# | Clone libraries from Github                                                |
# +----------------------------------------------------------------------------+

git clone https://github.com/emelianov/modbus-esp8266
git clone https://github.com/esp8266/Arduino
git clone https://github.com/arduino-libraries/NTPClient
